# Generated by Django 6.0.2 on 2026-03-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimatedTime',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='timeSpent',
            field=models.IntegerField(default=0),
        ),
    ]
